project_id = "kfohdchzbiesnguwnfmr"

[functions.mercadopago-webhook]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.create-google-meet]
verify_jwt = true

[functions.appointment-payment-create]
verify_jwt = true

[functions.appointment-payment-webhook]
verify_jwt = false

[functions.check-calendar-availability]
verify_jwt = false

[functions.mercadopago-one-time-payment]
verify_jwt = true

[functions.admin-email-create-campaign]
verify_jwt = true

[functions.admin-email-process-queue]
verify_jwt = true

[functions.email-unsubscribe]
verify_jwt = false
